<?php

/** 
  * Implements hookhook_field_formatter_info()
  */
function jigsaw_field_formatter_info()
{
	return array(
		'jigsaw_default_formatter' => array(
			'label' => t('Jigsaw'),
			'field types' => array('text_long'),
			),
			);
}
/**
   * Implements hook_field_formatter_view().
    */
function jigsaw_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) 
{
	$element = array();
	switch ($display['type']) {
		case 'jigsaw_default_formatter' :
			foreach ($items as $delta=>$item) {
				$vals =  (isset($item['value']) && $item['value'])
					? unserialize($item['value'])
					: array();

				$element[$delta]['#markup'] = jigsaw_view_piece($vals);
			}
			return $element;
			break;
	}
}

/**
  * Implements hook_field_widget_info()
  */
function jigsaw_field_widget_info()
{
	return array( 'jigsaw_default_widget' =>array(
		'label' => t('Jigsaw widget'),
		'field types' => array('text_long'),
		));
}


//function jigsaw_field_widget_form {{{
/** 
  * Implements hook_field_widget_form()
  */
function jigsaw_field_widget_form( &$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element ) {
	
	// $instance[widget][type] == jigsaw_default_widget because there's only one implemented.
	$element += array(
			'#type' => 'fieldset',
			'#element_validate' => array('jigsaw_default_widget_validate'),
			'#delta' => $delta,
			'#collapsible' => true,
			'#collapsed' => true,
			);
	$element['#title'] = "$field[field_name]:" . ($delta+1);
	// debug:	global $user; if ($user->uid ==1 && false) { drupal_set_message( "<pre>" .htmlspecialchars(print_r($field,1)) ."</pre>"); }

	// unpack existing data
	$vals =  (isset($items[$delta]['value']) && $items[$delta]['value'])
		? unserialize($items[$delta]['value'])
	   	: array();

	$vals += array('jigsaw_type'=>'raw','jigsaw_data'=>'','jigsaw_behaviour'=>'raw');

	$element['jigsaw_type'] = array(
		'#title' => t('Type'),
		'#type' => 'select',
		'#options' => array(
			'raw' => 'Embed HTML code copied from another site',
			'src-php' => 'PHP code to pretty print',
			),
		'#default_value' => $vals['jigsaw_type'],
		);
	$element['jigsaw_behaviour'] = array(
		'#title' => t('Presentation'),
		'#type' => 'select',
		'#options' => array(
			'raw' => 'As-is',
			'overlay' => 'Overlay',
			),
		'#default_value' => $vals['jigsaw_behaviour'],
		);
	$element['jigsaw_data'] = array(
		'#title' => t('Enter content'),
		'#type' => 'textarea',
		'#default_value' => $vals['jigsaw_data'],
		);
	
	return $element;
} //}}}

// function jigsaw_default_widget_validate( $element, &$form_state ){{{
/**
  * validation hook set in #element_validate
  */
function jigsaw_default_widget_validate( $element, &$form_state ) {

	// get field definition
    // $field = field_widget_field($element, $form_state);
	// get instance definition 
	//$instance = field_widget_instance($element, $form_state);

	// get the field_name of the fieldset
	$field_name = $element['#field_name'];
	// which fieldset set is being edited
	$delta = $element['#delta'];
	$lang  = $element['#language'];

	if (!empty($form_state['values'][$field_name][$lang][$delta]['jigsaw_data'])) {
		$values = $form_state['values'][$field_name][$lang][$delta];

		/* here could validate $values['jigsaw_type'] and $values['jigsaw_data']
		   and call form_set_error().
		   */

		// need to create composite value for field
		// this is just the PHP serialized version
		form_set_value($element, array( 'value' => serialize($values)), $form_state);
	}
	else form_set_value($element, array( 'value' => NULL), $form_state);
} //}}}

// function jigsaw_view_piece($data){{{
function jigsaw_view_piece($data)
{
	static $delta;
	if (!isset($delta)) $delta=0;

	// ensure defaults
	$data += array( 'jigsaw_type'=>'raw','jigsaw_data'=>'','jigsaw_behaviour'=>'raw');

	$html = '';

	// Raw output
	if ($data['jigsaw_type'] == 'raw')
		$html = $data['jigsaw_data'];

	if ($data['jigsaw_type'] == 'src-php')
	{
		$html = highlight_string($data['jigsaw_data'],1);
	}

	// behaviour
	if ($data['jigsaw_behaviour'] != 'raw') {
		// give javascript the html
		$json = json_encode($html);

		$html = "<div class='jigsaw $data[jigsaw_behaviour]' id='jigsawPiece$delta' ><script type='text/javascript'>window.jigsawPiece$delta = $json ;</script></div>";
		drupal_add_js( drupal_get_path('module','jigsaw') . '/jigsaw.js' );
		drupal_add_css( drupal_get_path('module','jigsaw') . '/jigsaw.css' );
	}
	return $html;
} //}}}

